security:  
    encoders:        
        App\Entity\User: bcrypt

    providers:
        database:
            entity:
                class: App\Entity\User
                property: username 

    firewalls:      
        user_area:
            pattern: ^/login
            security: false
            
        secured_area:
            pattern: ^/
            security: false
            provider: database
            
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /home

            logout:
                path: /logout
                target: /login