security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        app-main:
            pattern: ^/
            security: false
            request_matcher:      ~
            access_denied_url:    /access-denied
            
            form_login:
                check_path: /login_check
                login_path: /login
   
                
            logout:
                path:   /logout
                target: /
                invalidate_session: false

      
